### ISSUE TITLE
Add support for defining actions associated to interface Ids

### ISSUE THREAD

**Issue by pefribeiro** [izissise/network-manager-connection-action#2]
First of all, thanks for your awesome dbus-based monitor!

**Is your feature request related to a problem? Please describe.**
In my use case I have a connection to a GlobalProtect VPN I'd like to monitor. However, each time a connection is (re-)established it gets a new uuid, making it impossible to define an action based on a specific uuid.

**Describe the solution you'd like**
I'd like the ability to configure actions in terms of interface names. Eg:
```
[connections."eth0"]
name = "Eth0"
context = ""
up-script = "systemctl --user restart krb.service"
down-script = "systemctl --user stop krb.service"
```

**Describe alternatives you've considered**
N/A

**Additional context**
I've made a fork of the code and implemented support for configuring actions based on device Ids in addition to uuids. I'll submit a pull request with my suggested changes.

**Comment by izissise** [comment]
Thanks a lot, I made a new release with your changes
