### ISSUE TITLE
Question: How is this better / faster than NM dispatcher scripts?

### ISSUE THREAD

**Issue by Strykar** [izissise/network-manager-connection-action#4]
I heard of this project at https://askubuntu.com/questions/1111652/network-manager-script-when-interface-up and am wondering how using this would be better and in which way compared to using dispatcher scripts managed by NetworkManager as suggested in the link.

**Comment by izissise** [comment]
Hello, The main advantage would be that, the scripts wouldn't be running as root but as the user which runs the service

**Comment by Strykar** [comment]
Thank you for clearing that up!

**Comment by TheFern2** [comment]
Nice project btw @izissise just perfect for what I need it, to run a script per connection, I just tested on our armv7 devices, and it works great I like the simplicity for what it does.

@Strykar Just out of my own curiosity have you implemented something similar in with dispatcher scripts? Would you just use dbus-monitor and monitor state changed and then check conn name to run some script or command? I am just trying to gauge how much script work would it take.

**Comment by TheFern2** [comment]
@Strykar nvm is pretty easy to use dispatcher scripts https://man.archlinux.org/man/NetworkManager-dispatcher.8.en

```bash
#!/bin/bash

if [ "$NM_DISPATCHER_ACTION" = "up" ]; then
    logger "Network connection is up, $CONNECTION_ID, $DEVICE_IFACE"
    
    if [ "$CONNECTION_ID" = "att" ]; then
        echo "Doing att stuff" >> ~/testfile2
    elif [ "$CONNECTION_ID" = "vzw" ]; then
        echo "Doing vzw stuff"  >> ~/testfile2
    fi
elif [ "$NM_DISPATCHER_ACTION" = "down" ]; then
    logger "Network connection is down, $CONNECTION_ID, $DEVICE_IFACE"
# elif [ "$NM_DISPATCHER_ACTION" = "connectivity-change" ]; then
#     logger "Network connection change, $CONNECTION_ID, $DEVICE_IFACE"
fi
```

**Comment by Strykar** [comment]
@TheFern2  - https://wiki.archlinux.org/title/NetworkManager#Network_services_with_NetworkManager_dispatcher

**Comment by izissise** [comment]
It would be nice if the interface of network-manager-connection-action be compatible with dispatcher

**Comment by TheFern2** [comment]
You mean like sourcing all the dispatcher.d env variables? or I guess you could read the data from the bus too. I agree that would be nice.
